### ISSUE TITLE
ClientSessionListener throws com.google.inject.OutOfScopeException

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eurekaclinical-common#7]
For example:
```
INFO: Destroying session for client org.eurekaclinical.user.client.EurekaClinicalUserClient for service /eureka-webapp
Aug 24, 2017 3:48:53 PM org.apache.catalina.session.StandardSession expire
SEVERE: Session event listener threw exception
com.google.inject.ProvisionException: Guice provision errors:

1) Error in custom provider, com.google.inject.OutOfScopeException: Cannot access scoped object. Either we are not currently inside an HTTP Servlet request, or you may have forgotten to apply com.google.inject.servlet.GuiceFilter as a servlet filter for this request.
  at edu.emory.cci.aiw.cvrg.eureka.webapp.config.AppModule.configure(AppModule.java:80)
  while locating org.eurekaclinical.user.client.EurekaClinicalUserClient

1 error
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
	at org.eurekaclinical.common.config.ClientSessionListener.sessionDestroyed(ClientSessionListener.java:83)
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:806)
	at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:656)
	at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:532)
	at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:517)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1352)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1530)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1519)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.inject.OutOfScopeException: Cannot access scoped object. Either we are not currently inside an HTTP Servlet request, or you may have forgotten to apply com.google.inject.servlet.GuiceFilter as a servlet filter for this request.
	at com.google.inject.servlet.GuiceFilter.getContext(GuiceFilter.java:135)
	at com.google.inject.servlet.GuiceFilter.getRequest(GuiceFilter.java:121)
	at com.google.inject.servlet.ServletScopes$2$1.get(ServletScopes.java:114)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
	... 12 more
```
This appears to occur only when tomcat sweeps active sessions and cleans up any invalid ones. It appears to be a harmless error, but we should handle it (check isValid() ourselves?).

**Comment by arpost** [comment]
A potential solution is at https://github.com/google/guice/issues/97.

**Comment by arpost** [comment]
Fixed
